export const topics = {
    SurgicalBasicPrinciples: [
        'Random',
        'The Rise of Modern Surgery: An Overview',
        'Ethics and Professionalism in Surgery',
        'The Inflammatory Response',
        'Shock, Electrolytes, and Fluid',
        'Metabolism in Surgical Patients',
        'Wound Healing',
        'Regenerative Medicine',       
        'Critical Assessment of Surgical Outcomes and Health',      
        'Safety in the Surgical Environment',  
    ],
    PerioperativeManagement: [
        'Random',
        'Principles of Preoperative and Operative Surgery',
        'Surgical Infections and Antibiotic Use',
        'Surgical Complications',
        'Surgery in the Geriatric Patient',       
        'Anesthesiology Principles, Pain Management, and Conscious Sedation',
        'Emerging Technology in Surgery: Informatics,Electronics',
        'Robotic Surgery',
    ],
   TraumaAndCriticalCare: [
        'Random',
        'Management of Acute Trauma',
        'The Difficult Abdominal Wall', 
        'Emergency Care of Musculoskeletal Injuries', 
        'Burns',
        'Bites and Stings', 
        'Surgical Critical Care',
        'Bedside Surgical Procedures',
        'The Surgeon’s Role in Mass Casualty Incidents',
    ],
    TransplantationAndImmunology: [
        'Random',
        'Transplantation Immunobiology and Immunosuppression', 
        'Liver Transplantation', 
        'Kidney and Pancreas Transplantation', 
        'Small Bowel Transplantation', 
    ],
    SurgicalOncology: [
        'Random',
        'Tumor Biology and Tumor Markers', 
        'Tumor Immunology and Immunotherapy', 
        'Melanoma and Cutaneous Malignancie', 
        'Soft Tissue Sarcoma',
        'Bone Tumors',
    ],
    HeadAndNeck: [
        'Random',
        ' Head and Neck',    
    ],
    Breast: [
        'Random',
        'Diseases of the Breast', 
        'Breast Reconstruction', 
    ],
    Endocrine: [
        'Random',
        'Thyroid', 
        'The Parathyroid Glands',
        'Endocrine Pancreas', 
        'The Adrenal Glands', 
        'The Multiple Endocrine Neoplasia Syndromes',
    ],
    Esophagus: [
        'Random',
        'Esophagus', 
        'Gastroesophageal Reflux Disease and Hiatal Hernia',
    ],
    Abdomen: [
        'Random',
        'Abdominal Wall, Umbilicus, Peritoneum, Mesenteries,omentum and Retroperitoneum',
        'Hernias',
        'Acute Abdomen', 
        'Acute Gastrointestinal Hemorrhage', 
        'Morbid Obesity',
        'Stomach',
        'Small Intestine',
        'The Appendix', 
        'Anus', 
        'The Liver', 
        'Biliary System',
        'Exocrine Pancreas', 
        'The Spleen', 
    ],
    Chest: [
        'Random',
        'Lung, Chest Wall, Pleura and Mediastinum',
        'Congenital Heart Disease', 
        'Acquired Heart Disease: Coronary Insufficiency', 
        'Acquired Heart Disease: Valvular',   
    ],
    Vascular: [
        'Random',
        'The Aorta',
        'Peripheral Arterial Disease',
        'Vascular Trauma',
        'Venous Disease',
        'The Lymphatics', 
    ],
    SpecialtiesInGeneralSurgery : [
        'Random',
        'Pediatric Surgery',
        'Neurosurgery',
        'Plastic Surgery',
        'Hand Surgery', 
        'Gynecologic Surgery', 
        'Surgery in the Pregnant Patient', 
        'Fetal Surgery', 
        'Urologic Surgery',
    ],

}
